// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD56MRy8InaRQ9TNzSnGCeZYnKscD2pAFI',
    appId: '1:1071335209511:web:930b87e2dd1b9a29502c02',
    messagingSenderId: '1071335209511',
    projectId: 'fastshop-app',
    authDomain: 'fastshop-app.firebaseapp.com',
    storageBucket: 'fastshop-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuLhX6pkKUR8e_RzvyN8K_eRc0RBdBAFc',
    appId: '1:1071335209511:android:79e2fd476d235ba2502c02',
    messagingSenderId: '1071335209511',
    projectId: 'fastshop-app',
    storageBucket: 'fastshop-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwoeI8Yabjff9W078e-hzAdwIJJxfcARc',
    appId: '1:1071335209511:ios:9b5ee16a5211854a502c02',
    messagingSenderId: '1071335209511',
    projectId: 'fastshop-app',
    storageBucket: 'fastshop-app.appspot.com',
    iosClientId: '1071335209511-p2nokl0gc7okqr0v3und110auhfrt92m.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwoeI8Yabjff9W078e-hzAdwIJJxfcARc',
    appId: '1:1071335209511:ios:9b5ee16a5211854a502c02',
    messagingSenderId: '1071335209511',
    projectId: 'fastshop-app',
    storageBucket: 'fastshop-app.appspot.com',
    iosClientId: '1071335209511-p2nokl0gc7okqr0v3und110auhfrt92m.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastshop',
  );
}
